package io.github.footermandev.tritium.settings

import com.typesafe.config.ConfigFactory
import com.typesafe.config.ConfigRenderOptions
import io.github.footermandev.tritium.TConstants
import io.github.footermandev.tritium.fromTR
import io.github.footermandev.tritium.io.VPath
import io.github.footermandev.tritium.logger
import java.io.File

/**
 * HOCON-backed storage for settings grouped by namespace.
 *
 * Each namespace is persisted to its own `*.conf` file under [rootDir].
 *
 * @property rootDir Root directory containing namespace settings files.
 * @see SettingsMngr
 */
class HoconSettingsStore(
    private val rootDir: VPath = fromTR(TConstants.Dirs.SETTINGS)
) {
    private val logger = logger()
    private val renderOpts: ConfigRenderOptions = ConfigRenderOptions.defaults()
        .setJson(false)
        .setComments(false)
        .setOriginComments(false)

    /**
     * Encoded setting entry written to disk.
     *
     * @property key Local setting id.
     * @property renderedValue Pre-rendered HOCON value.
     * @property comments Comment lines rendered above the setting.
     * @property commentOnly When `true`, only comments are emitted and value is omitted.
     */
    data class EncodedSetting(
        val key: String,
        val renderedValue: String,
        val comments: List<String> = emptyList(),
        val commentOnly: Boolean = false
    )

    init {
        try {
            rootDir.mkdirs()
        } catch (t: Throwable) {
            logger.warn("Failed to ensure settings dir exists at {}", rootDir, t)
        }
    }

    /**
     * Reads raw HOCON-rendered values for [namespace].
     *
     * @param namespace Namespace whose settings file should be read.
     * @return Map of local setting id to rendered HOCON value.
     * @see write
     */
    fun read(namespace: String): Map<String, String> {
        val file = namespaceFile(namespace)
        if (!file.exists()) return emptyMap()

        val config = ConfigFactory.parseFile(file)
        if (!config.hasPath("settings")) return emptyMap()

        val settingsCfg = config.getConfig("settings")
        return settingsCfg.root().entries.associate { entry ->
            val rendered = entry.value.render(renderOpts)
            entry.key to rendered
        }
    }

    /**
     * Writes [entries] for [namespace] to disk.
     *
     * Existing file content is replaced with a generated settings block sorted by key.
     *
     * @param namespace Namespace to persist.
     * @param entries Encoded setting entries to write.
     * @see read
     */
    fun write(namespace: String, entries: List<EncodedSetting>) {
        if (entries.isEmpty()) return
        val file = namespaceFile(namespace)
        val sorted = entries.sortedBy { it.key }
        val body = buildString {
            appendLine("# Generated by Tritium. Manual edits are kept where possible.")
            appendLine("settings {")
            sorted.forEach { entry ->
                val comments = entry.comments
                    .map { it.trim() }
                    .filter { it.isNotEmpty() }
                comments.forEach { comment -> appendLine("  # $comment") }
                if (entry.commentOnly) {
                    if (comments.isNotEmpty()) {
                        appendLine()
                    }
                    return@forEach
                }
                val key = quoteKey(entry.key)
                val rendered = entry.renderedValue.trim()
                val multiLine = rendered.contains("\n")
                if (multiLine) {
                    append("  $key = ")
                    appendLine(rendered.prependIndent("  ").trimEnd())
                } else {
                    appendLine("  $key = $rendered")
                }
                appendLine()
            }
            appendLine("}")
        }

        file.parentFile?.mkdirs()
        file.writeText(body)
    }

    /**
     * Resolves the namespace settings file location.
     *
     * @param namespace Namespace to resolve.
     * @return Target file for namespace persistence.
     */
    private fun namespaceFile(namespace: String): File = rootDir.resolve("$namespace.conf").toJFile()

    /**
     * Quotes and escapes a local key for HOCON output.
     *
     * @param key Raw local setting key.
     * @return Quoted and escaped key string.
     */
    private fun quoteKey(key: String): String = "\"${key.replace("\"", "\\\"")}\""
}
